"""
Django settings for lab1 project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path


# Определение базовой директории проекта
BASE_DIR = Path(__file__).resolve().parent.parent

# Секретный ключ для подписи данных (не хранить в открытом виде в продакшене)
SECRET_KEY = 'django-insecure-6etu+@qw27&h0q9l1o)gsa!pha897yh&4e-+7m)s65&icq(s)#'

# Режим отладки (включать только при разработке)
DEBUG = True

# Разрешенные хосты, с которых можно обращаться к приложению
ALLOWED_HOSTS = []


# Определение установленных приложений
INSTALLED_APPS = [
    'django.contrib.admin',  # Админ-панель
    'django.contrib.auth',  # Аутентификация и управление пользователями
    'django.contrib.contenttypes',  # Поддержка контентных типов
    'django.contrib.sessions',  # Сессии пользователей
    'django.contrib.messages',  # Сообщения
    'django.contrib.staticfiles',

    'rest_framework',
    'corsheaders',
    'rest_framework.authtoken',

    'mainapp'  # Пользовательское приложение
]

# Промежуточное ПО (Middleware) для обработки запросов
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',  # Защита от некоторых атак
    'django.contrib.sessions.middleware.SessionMiddleware',  # Поддержка сессий
    'django.middleware.common.CommonMiddleware',  # Общие настройки HTTP
    'django.middleware.csrf.CsrfViewMiddleware',  # Защита от CSRF-атак
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # Аутентификация пользователей
    'django.contrib.messages.middleware.MessageMiddleware',  # Поддержка системы сообщений
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # Защита от кликджекинга
]

# Корневой конфигурационный файл маршрутов
ROOT_URLCONF = 'lab1.urls'

# Настройки шаблонов
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',  # Используемый бэкенд шаблонов
        'DIRS': [],  # Пути к пользовательским шаблонам (если есть)
        'APP_DIRS': True,  # Поиск шаблонов внутри приложений
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',  # Отладочная информация
                'django.template.context_processors.request',  # Доступ к объекту request в шаблонах
                'django.contrib.auth.context_processors.auth',  # Данные о пользователе
                'django.contrib.messages.context_processors.messages',  # Сообщения для пользователей
            ],
        },
    },
]

# WSGI-приложение (точка входа для развертывания)
WSGI_APPLICATION = 'lab1.wsgi.application'


# Настройки базы данных
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'lab1_db',
        'USER': 'django',
        'PASSWORD': '338733',
        'HOST': 'postgres-service',
        # 'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Валидация паролей (правила безопасности)
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',  # Проверка на схожесть с данными пользователя
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',  # Минимальная длина пароля
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',  # Проверка на распространенные пароли
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',  # Проверка на полностью числовые пароли
    },
]


# Настройки локализации
LANGUAGE_CODE = 'en-us'  # Язык проекта

TIME_ZONE = 'UTC'  # Часовой пояс

USE_I18N = True  # Включение поддержки интернационализации

USE_TZ = True  # Включение поддержки часовых поясов


# Настройки статических файлов (CSS, JS, изображения)
STATIC_URL = 'static/'  # URL-адрес для доступа к статическим файлам
STATIC_ROOT = '/staticfiles'

# Тип поля по умолчанию для первичных ключей моделей
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
