# Generated by Django 5.1.6 on 2025-02-28 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_author_first_name_alter_author_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='borrowrecord',
            name='book',
        ),
        migrations.RemoveField(
            model_name='borrowrecord',
            name='reader',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BorrowRecord',
        ),
        migrations.DeleteModel(
            name='Reader',
        ),
    ]
